version: "3"

networks:
  default:

services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
    - .:/var/www
    networks:
      - default

  nginx:
    container_name: nginx
    image: nginx
    env_file:
      - ./.env
    ports:
    - ${NGINX_PORT}:80
    volumes:
    - .:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
    - app
    networks:
      - default

  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.env
    ports:
    - ${DATABASE_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    networks:
      - default

volumes:
  db:
